spring:
  application:
    name: spring-batch
  datasource:
    hikari:
      jdbc-url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
      username: ${POSTGRES_USERNAME:root}
      password: ${POSTGRES_PASSWORD:root}
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    job:
      name: job
      enabled: false
    jdbc:
      initialize-schema: always
      table-prefix: batch_
app:
  datasource:
    hikari:
      jdbc-url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/app_batch}
      username: ${POSTGRES_USERNAME:root}
      password: ${POSTGRES_PASSWORD:root}
      driver-class-name: org.postgresql.Driver
file:
  input: test.csv
spring-batch-learning:
  output-folder: ./files/output/


